### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [artsy/reaction#1103]
Hello. I want to help the project. Do you want me to make a logo for you?

**Comment by l2succes** [comment]
@ritalinn Yes! That would be awesome. We appreciate the help 🤗

**Comment by orta** [comment]
I ended up building one:

<img width="854" alt="Screen Shot 2019-05-02 at 9 26 54 AM" src="https://user-images.githubusercontent.com/49038/57078543-75f2ab00-6cbc-11e9-9850-f457905581c8.png">
