### ISSUE TITLE
[RFC] Enable type checking for tests

### ISSUE THREAD

**Issue by ds300** [artsy/reaction#1166]
# Proposal
Delete this line in tsconfig.json:

![image](https://user-images.githubusercontent.com/1242537/44465733-52983c00-a616-11e8-87c3-e7c45777a7bd.png)

# Reasoning
- This will allow the typescript compiler to check for type errrors in test files, which is extra armour on top of the tests themselves.

- I can imagine API changes that don't cause a test to fail but might still cause the test's code to be an out-of-date usage example for that particular API.

- The vscode TS plugin currently doesn't work properly in test files because it has the default contextless TS config applied, rather than our own tsconfig.json file. This means that, e.g. absolute import paths show up as errors, but work fine when run under jest:

    ![image](https://user-images.githubusercontent.com/1242537/44465957-f681e780-a616-11e8-886e-ce3fd9e3c37f.png)

   And of course if you choose to write test code that would fail type checking, you get other red squiggly lines that just add noise.

    ![image](https://user-images.githubusercontent.com/1242537/44467548-0ac7e380-a61b-11e8-89d1-f304b1ba40ce.png)

# Exceptions
Sometimes we don't care about types, or they get in the way. I would therefore recommend use of `any` or `@ts-ignore` or even `.js` files if our setup supports that?

# How
Turning type-checking on for test files and running `tsc` introduces 243 errors. It would be a big old PR to fix them all in one go. So I'd recommend doing it in a staggered way:

1. Turn on type-checking for tests
2. Fix a handful of erroring test files
3. If there are still erroring test files left over then turn off type-checking for tests
4. Submit PR
5. If there are still erroring test files left over then go to 1.

**Comment by orta** [comment]
> .js files if our setup supports that

They do, that can be fine 👍 (and the `// @ts-ignore`)

---

I think we did this intentionally because we were teaching web folk typescript from coffeescript, and then never went back to change the setting once everyone was comfortable.

**Comment by damassi** [comment]
I've been running into this for a few days now! Very much in favor, but I think there's a significant amount of work that will need to take place in order to get the type-checking to pass which will involve introducing a lot of `any`'s. 

(I'm not in favor of turning on `noImplicitAny`, though, since writing solid types is a different kind of work than shipping features under deadlines. If there are other ways to make the compiler stricter I'm in favor. I'm also all for RFC'ing this.)

**Comment by orta** [comment]
TS 3.0 allows (via) projects, the ability to *I think* have different parts of the code base with different compilation rules.  https://www.typescriptlang.org/docs/handbook/project-references.html

**Comment by damassi** [comment]
I just remembered what I did a last year to get around type-checking in tests was to use `.jsx` as the extension rather than `.tsx`. I'm not suggesting that we do that here just that it might be a good work-around for older tests.

**Comment by ds300** [comment]
I'm going to resolve this RFC now

## Resolution
We decided to do it.

## Level of Support
2: Positive feedback.

## Next Steps
We will implement it. I'll start doing chunks in my 20% time. Anyone who wants to help out, please do! 🙏

**Comment by damassi** [comment]
If we can figure out a plan to divide work I'll help this along. Thinking we maybe open a chore PR in Reaction (not from a fork) where anyone can contribute?

**Comment by ds300** [comment]
Great! It would be dope to have help :+1:

I'm not keen on the idea of a big, long-lived PR. Feedback can get messy, ownership gets fuzzy, and keeping up to date with master can be a pain.

How about if we create a Jira ticket with subtasks for all the files that have failing tests, and then if people want to help out, they can pick off the ones they like at any pace, and submit PRs for whatever small chunks they get done in a session?

**Comment by damassi** [comment]
That seems better 👍

**Comment by orta** [comment]
You could turn types on for dev, then turn it back off when merging PRs?

**Comment by ds300** [comment]
Yep that's the plan :+1: The 'how' section of this RFC gives more details.

**Comment by ds300** [comment]
I'm going to close this since the RFC has been resolved.

**Comment by damassi** [comment]
This work was completed in https://github.com/artsy/reaction/pull/1458
