### ISSUE TITLE
Jest test regex could be optimized

### ISSUE THREAD

**Issue by erikdstock** [artsy/reaction#1285]
In `package.json`, the regex:
```json
   "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js|jsx)$",
```
includes both the file `src/__tests__/blah.test.js` and `src/__tests__/testHelpers.js`, which meant that I had to put a support file outside the Order App's `__tests__` folder. We could improve it by changing the start to not use the `|` operator: `/__tests__/.*\\.(test|spec).(ts...etc)$`, but this causes the number of suites to drop, so some stragglers would probably have to have their names updated.

**Comment by orta** [comment]
in the upcoming jest, I think we can remove this completely as the regex now supports TS also
