### ISSUE TITLE
Login error not showing friendly message on incorrect email/password

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction#150]
Reported by @tayapage6 , I can repro:

![pasted image at 2017_05_05 12_26 pm](https://cloud.githubusercontent.com/assets/1457859/25808516/512cbdca-33d8-11e7-9f7c-d5803f29eeaa.png)

**Comment by alloy** [comment]
Is this still an issue?

**Comment by dblandin** [comment]
I don't believe this is still an issue so I'm going to go ahead and close.

**Comment by alloy** [comment]
Spring cleaning 2020 👌 

![](https://media.giphy.com/media/z5fNH8BMbeDN6/giphy.gif)
