### ISSUE TITLE
Line-height is extremely large on a few elements after responsive typography update

### ISSUE THREAD

**Issue by pepopowitz** [artsy/reaction#1535]
When we merged [this PR](https://github.com/artsy/reaction/pull/1531), we ended up with a couple of elements that suddenly had very large line-heights. See [here](https://github.com/artsy/reaction/pull/1531#issuecomment-437709780) and [here](https://github.com/artsy/reaction/pull/1531#issuecomment-437709971) for screenshots.

In looking at these examples, it looks like the "extra tall" components are all specifying a `lineHeight={18}` prop, like this:

```
  <Serif mb={1} size="3t" color="black100" lineHeight={18}>
    Country
  </Serif>
```

I suspect that this broke when we updated the styled-system dependency - we noticed similar issues in the development of #1531, where it seemed to switch from a default of pixels to a default of ems. 

We should either add back support for `lineHeight={18}`, or update these elements to specify `lineHeight="18px"`.

**Comment by pepopowitz** [comment]
@alloy @zephraph Do either of you have thoughts on whether `lineHeight={18}` should be supported as it was previously, or these lines should be changed to `lineHeight="18px"`?

**Comment by zephraph** [comment]
We shouldn't be explicitly setting the lineHeight like this. If it _has_ to be set, we should do what you said in the latter part of your suggesting... just set it to `18px`. This is a code smell to me though.

**Comment by alloy** [comment]
I’m no CSS expert, but isn’t `line-height` also used to vertically center text in a box? Anyways, in terms of the actual fix I’ll defer to you two 👍

**Comment by pepopowitz** [comment]
In these examples, `line-height` is being used to adjust the height of the label, to match the `line-height` set by the other input fields. They are different, because....

Most input fields on the forms use the `<Input>` component - which uses the [Garamond s17 font specified in src/assets/fonts.tsx](https://github.com/artsy/reaction/blob/master/src/Assets/Fonts.tsx#L20) for the label. That gives them a line height of 1.1em. 

These one-off fields render a `<Serif>` component for the label. They specify `size="3t"`, which gives them a matching font-size, but a non-matching line-height (20px instead of 18px). 

I'm going to change these three examples to specify line-height of "1.1em", to match the `<Input>` component labels more precisely.

**Comment by zephraph** [comment]
This was fixed a while back. Gonna close the issue.
