### ISSUE TITLE
State of testing Relay powered components

### ISSUE THREAD

**Issue by alloy** [artsy/reaction#1604]
We’ve been trying a few different things and haven’t settled on a solution yet that satisfies all the, in my mind, requirements. So I figured it might be time to write up those requirements, the things we’ve experimented with, and what the final solution could be.

# Requirements

- **Exercise fragments:** to verify that fragments select the correct fields.
- **Exercise containers:** to verify that container configuration is correct (really only refetch/pagination containers).
- **Easy to use:** i.e. easy to provide required mock data (typed data highly preferable).
- **Fast tests:** because slow tests scale badly.

# Tried options

## RelayStubProvider

This approach mocks all of the Relay API and inserts data directly into the components. An example can be found [here](https://github.com/artsy/reaction/blob/9d8376d4960c83114084a5bb2c99f1348ea98d0b/src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/__tests__/ArtworkContextAuction.test.tsx#L11-L15)

- [ ] **Exercise fragments:** Some coverage could be provided by using the types emitted for the fragment, but those also only go 1 level deep and thus don’t cover children of the container.
- [ ] **Exercise containers:** None
- [x] **Easy to use:**
- [x] **Fast tests:**

## relay-mock-network-layer / renderRelayTree

This approach mocks our schema, uses a Relay network layer that directly queries the mocked schema, and uses `renderRelayTree` to keep rendering the React tree until the Relay containers have all rendered.

- [x] **Exercise fragments:** Actual queries are performed.
- [x] **Exercise containers:** No Relay APIs are mocked.
- [ ] **Easy to use:** Figuring out what data to provide and how to provide it has been a constant pain. The graphql-tools `addMockFunctionsToSchema` functionality provides little guidance in what data is missing and how it should be mocked.
- [ ] **Fast tests:** Everything related to the network layer is async, so we need to update, poll, and scan the tree continuously to know if the containers have been rendered, which is turning out to be too slow.

I _could_ see us extending Relay to emit types for all containers in the entire tree, which would make stubbing the schema exactly according to those types trivial. The only additional change needed would be for `addMockFunctionsToSchema` to infer what aliased fields to stub based on the passed in data. (Currently if in our fragments we select e.g. `foo: bar`, where `foo` is an alias of the `bar` field, `addMockFunctionsToSchema` expects us to mock the `bar` field.)

# Next options

## Entire mocked copy of our GraphQL service

We haven’t done this yet, but an option I discussed with @ds300 was to add a ‘VCR’ library to our GraphQL service that would be able to record all the possible upstream requests and replay those when importing the service into our component libraries.

- [x] **Exercise fragments:** Same as relay-mock-network-layer / renderRelayTree
- [x] **Exercise containers:** relay-mock-network-layer / renderRelayTree
- [x] **Easy to use:** Unlike relay-mock-network-layer / renderRelayTree, there wouldn’t be a need to do any data mocking, because the real data that our service provides has already been captured. (Albeit limited in permutations of the data.)
- [ ] **Fast tests:** Same as relay-mock-network-layer / renderRelayTree

## Use Relay store API

Relay has an imperative store API, which we thus far have interacted with only when updating the store after mutations, but this is what the Relay library tests use.

- [x] **Exercise fragments:** Need to verify this, but as Relay uses the fragments to select data from [the normalised store](https://facebook.github.io/relay/docs/en/runtime-architecture.html#data-model), I _think_ this could be enough to ensure the fragments select the right data.
- [x] **Exercise containers:** No mocking of container APIs.
- [x] **Easy to use:** We could easily add the ability to Relay to emit types for an entire tree and then create an API that would insert that data into the store.
- [x] **Fast tests:** Once data is in the store, we can tell a `QueryRenderer` to _synchronously_ render data that’s already available in the store.

**Comment by alloy** [comment]
For now I’m thinking of starting work on making Relay emit types for the entire tree and update `addMockFunctionsToSchema` to automatically handle aliased fields, because that should ease the current pain points of “relay-mock-network-layer / renderRelayTree”, but also be a stepping stone to the “Use Relay store API” option.

**Comment by javamonn** [comment]
We recently ported the `relay-mock-network-layer` / `MockRelayRenderer` to emission: https://github.com/artsy/emission/pull/1209. Potentially it'd be great to see the next iteration of this tooling broken out into a separate package so that we could keep up to date in Emission more easily as well. Alternatively, I can see the argument for waiting for the implementation to settle before lifting out into a separate package.

**Comment by damassi** [comment]
> For now I’m thinking of starting work on making Relay emit types for the entire tree

@alloy - this is TypeScript dependent, right? Are there any alternatives to this approach so that we could keep it broadly available to the JS ecosystem?

**Comment by alloy** [comment]
Type emitting would either happen immediately in Relay upstream or eventually, if by more broadly you mean Flow?

**Comment by damassi** [comment]
👍 Thats what I was thinking; wanted to clarify re https://github.com/relay-tools/relay-compiler-language-typescript

**Comment by josephsavona** [comment]
Using the Relay environment/store API definitely seems like the most flexible option. 

> emit types for an entire tree and then create an API that would insert that data into the store.

Do you mean a flow type describing the shape of the full query response? I’m curious how having a flow type to describe that would be helpful - for a lot of products that could also be a gigantic flow type.

**Comment by alloy** [comment]
> Do you mean a flow type describing the shape of the full query response? I’m curious how having a flow type to describe that would be helpful

@josephsavona Yeah that’s what I meant. It would be helpful in knowing all the fixture data that the dev needs to provide _without_ reading all of the fragments of the containers involved and looking up the types of the fields selected in those fragments.

> for a lot of products that could also be a gigantic flow type.

True, I should clarify that we currently have query renderers in our tests for subsets of an entire product view, so the data tree would be significantly smaller.

----

An example of what I’d imagine a test would look like:

```tsx
// ArtworkMetadata.tsx

import { createFragmentContainer, graphql } from "react-relay"
import { ArtworkMetadata_artwork } from "__generated__/ArtworkMetadata.graphql"

export const ArtworkMetadata: React.SFC<{ artwork: ArtworkMetadata_artwork }> = createFragmentContainer(
  ({ artwork }) => <span>{artwork.title} – {artwork.artist.name}</span>,
  graphql`
    fragment ArtworkMetadata_artwork on Artwork {
      title
      artist {
        name
      }
    }
  `
)
```

```tsx
// ArtworkBrick.tsx

import { createFragmentContainer, graphql } from "react-relay"
import { ArtworkBrick_artwork } from "__generated__/ArtworkBrick.graphql"

export const ArtworkBrick: React.SFC<{ artwork: ArtworkBrick_artwork }> = createFragmentContainer(
  ({ artwork }) => <div><img src={artwork.image.url} /><ArtworkMetadata artwork={artwork} /></div>,
  graphql`
    fragment ArtworkBrick_artwork on Artwork {
      image {
        url
      }
      ...ArtworkMetadata_artwork
    }
  `
)
```

```tsx
// ArtworkBrick.test.tsx

import { graphql, QueryRenderer } from "react-relay"
import { mount } from "enzyme"
import { ArtworkBrickTestQuery, ArtworkBrickTestQueryUnmaskedResponse } from "__generated__/ArtworkBrick.test.graphql"

const query = graphql`
  query ArtworkBrickTestQuery($artworkID: ID!) {
    artwork(id: $artworkID) {
      ...ArtworkBrick_artwork
    }
  }
`

describe("ArtworkBrick", () => {
  it("renders synchronously", () => {
    // The ArtworkBrickTestQueryUnmaskedResponse provides guidance with what data is required.
    const environment = mockEnvironmentWithStore<ArtworkBrickTestQueryUnmaskedResponse>(
      {
        artwork: {
          title: "Monkey Sign",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/L52FHh7v_f9mZ3QkC_2YJA/thumbnail.jpg"
          }
          artist: {
            name: "Banksy"
          }
        }
      }
    )

    const tree = mount(
      <QueryRenderer<ArtworkBrickTestQuery>
        dataFrom={STORE_THEN_NETWORK}
        environment={environment}
        query={query}
        variables={{ artworkID: "banksy-monkey-sign" }}
        render={props => <ArtworkBrick artwork={props.artwork}}
      />
    )

    expect(tree.find("span").text).toEqual("Monkey Sign - Banksy")
    // etc
  })
})
```

**Comment by alloy** [comment]
@josephsavona Done 👍 https://github.com/facebook/relay/issues/2597

**Comment by estrada9166** [comment]
Hi! Have you try [easygraphql-tester](https://github.com/EasyGraphQL/easygraphql-tester) just pass the schema and it's pretty much done! 
This is how it works!
```
'use strict'

const EasyGraphQLTester = require('easygraphql-tester')
const fs = require('fs')
const path = require('path')

const userSchema = fs.readFileSync(path.join(__dirname, 'schema', 'user.gql'), 'utf8')
const familySchema = fs.readFileSync(path.join(__dirname, 'schema', 'family.gql'), 'utf8')

const tester = new EasyGraphQLTester([userSchema, familySchema])

const query = `
  {
    getUser(id: "1") {
      id
      name
      familyInfo {
        lastName
        email
      }
    }
  }
`

const fixture = {
  id: '1',
  name: 'EasyGraphQL'
}

const { getUser } = tester.mock({ query, fixture })
```
And this is the result!
```
// getUser
{ 
  id: '1',
  name: 'EasyGraphQL',
  familyInfo: [
    { 
      lastName: 'Bartoletti',
      email: 'YSjsYuV@wtnK.com'
    },
    { 
      lastName: 'Bartoletti',
      email: 'YSjsYuV@wtnK.com'
    },
    { 
      lastName: 'Bartoletti',
      email: 'YSjsYuV@wtnK.com'
    }
  ]
}

```
So, you don't have to create the mocks, it'll do it for you! also, you can set fixtures and save them so you can access latter.

Also, [here is a demo](https://repl.it/@alejandroestrada/mock-easygraphql-tester)
