### ISSUE TITLE
Precompile when running from git

### ISSUE THREAD

**Issue by eessex** [artsy/reaction#178]
When running directly from git rather than NPM, `"@artsy/reaction-force": "git://github.com/artsy/reaction-force.git"`, need a build command to compile the dist folder

**Comment by orta** [comment]
Considering how simple it is to deploy, maybe it's fine to just have people use yarn and deploy often.

**Comment by alloy** [comment]
npm 5 now supports this through a `prepare` script entry in `package.json`: https://twitter.com/maybekatz/status/860363896443371520

Don’t know if yarn supports this too yet.

**Comment by damassi** [comment]
Closing now since deployments are much more seamless
