### ISSUE TITLE
Consider re-naming to "reaction"

### ISSUE THREAD

**Issue by orta** [artsy/reaction#179]
It's available: https://github.com/artsy/reaction

The scope of Reaction-Force is slowly growing as other teams expand into using this repo, perhaps it's worth changing the name of the repo ( and the tagline )

/cc @sweir27

**Comment by mzikherman** [comment]
I am down.

**Comment by alloy** [comment]
Agreed.

**Comment by orta** [comment]
It's done 👍

**Comment by orta** [comment]
Only breaking change from this will be the URL for the storybooks

**Comment by alloy** [comment]
@orta Oh yeah, be sure to send a PR to the storybooks repo to update their examples where we are featured!

**Comment by orta** [comment]
Good point!
