### ISSUE TITLE
Instructions on migrating Components from Reaction to Palette

### ISSUE THREAD

**Issue by damassi** [artsy/reaction#1903]
Hello! With our new design system increasingly being deployed across various apps it's becoming more important to consolidate shared components in one location -- Palette. Most of our common base elements have already been moved (`Box`, `Flex`, `Checkbox`, `Icons`, etc) but there are a few remaining items left (organized in order of perceived complexity):

- [x] [PriceRange](https://github.com/artsy/reaction/blob/master/src/Components/v2/PriceRange.tsx) (Devon  / https://github.com/artsy/palette/pull/199) 
  - [x] Removed from Reaction
- [x] [Pagination](https://github.com/artsy/reaction/blob/master/src/Components/v2/Pagination.tsx) (Adam / https://github.com/artsy/palette/pull/198 | https://github.com/artsy/reaction/pull/1907) 
  - [x] Removed from Reaction (though we still have a wrapper component for responsiveness)
- [x] [EntityHeader](https://github.com/artsy/reaction/blob/master/src/Components/v2/EntityHeader.tsx) (Oksana / https://github.com/artsy/palette/pull/202)
  - [x] Removed from Reaction
- [x] [Stepper](https://github.com/artsy/reaction/blob/master/
  - [x] Removed from Reactionsrc/Components/v2/Stepper.tsx) (Devon / https://github.com/artsy/palette/pull/210)
- [x] [ReadMore](https://github.com/artsy/reaction/blob/master/src/Components/v2/ReadMore.tsx) (Ashley+Devon / https://github.com/artsy/palette/pull/230)
  - [x] Removed from Reaction
- [x] [TimeRemaining](https://github.com/artsy/reaction/blob/master/src/Components/v2/CountdownTimer.tsx#L19-L42)  (Devon / https://github.com/artsy/palette/pull/203, https://github.com/artsy/palette/pull/201)
  - [x] Removed from Reaction
- [x] [ProgressBar](https://github.com/artsy/reaction/blob/master/src/Components/v2/CountdownTimer.tsx#L52-L83)  (Devon / https://github.com/artsy/palette/pull/204)
  - [ ] Removed from Reaction
- [x] [StaticCountdownTimer](https://github.com/artsy/reaction/blob/master/src/Components/v2/CountdownTimer.tsx#L85-L132) (Devon / https://github.com/artsy/palette/pull/205)
  - [x] Removed from Reaction

In each of the instances above the components have already been built with Palette so we can pretty much just copy / paste from Reaction into Palette and it will "just work". That said, there are a few caveats: 

- If a link above contains highlighted coded, that's all that should be moved since the other code in the file is more behavioral and relates to needs within Reaction, and / or has a data dependency. 
- A few files contain additional dependencies, for example `moment` or `lodash`. While we're moving components over it is **ok** to install additional dependencies (if totally necessary; for example `isString` from lodash can be replaced with `typeof thing === 'string'`, etc) so that the migration doesn't additionally require refactoring. **BUT** please make note of the dependency and add a `// FIXME` above the import so that we can keep Palette slender. 

When taking a component from up above, please edit this issue and add your name beside it so that we don't duplicate work.

## Suggested Workflow
https://github.com/artsy/palette/pull/199
For an example of a workflow checkout these previous PRs:
- [Palette: Add `<Tabs>` and `<Toggle>`](https://github.com/artsy/palette/pull/191)
- [Reaction: Remove `<Tabs> and <Toggle>`](https://github.com/artsy/reaction/pull/1897)

Thanks to TypeScript's type system this should be pretty painless, but there are a few steps:

1. Create a new folder in Palette under `elements` with the following structure:
```sh
  /elements/MyComponent
    index.tsx
    MyComponent.tsx
    MyComponent.ios.tsx
```

2. Back in Reaction, find the component you want to move and copy the contents
3. Paste the contents into `MyComponent.tsx` (the `.ios.tsx` file is there just as a stub) 
4. Make sure to update the `@artsy/palette` import path so that it [refers to local files](https://github.com/artsy/palette/blob/master/src/elements/Tabs/Tabs.tsx#L4-L5)
5. Start up the typechecker: `yarn type-check -w`. Fix any issues it finds
6. Go into the `index.tsx` file created up above and [export your new component](https://github.com/artsy/palette/blob/master/src/elements/Tabs/index.tsx#L1)
7. Navigate to the `/elements` index file and [then add another export](https://github.com/artsy/palette/blob/master/src/elements/index.tsx#L23) -- Make sure its alpha 😉 
8. Does everything type-check ok? Great, almost done...
9. Now, add some docs for the component. Boot the docs by running `yarn docs` and go to http://localhost:3000
10. Find the `/docs` folder and create a new `MyComponent.mdx` file. MDX is cool -- its Markdown + React. Check out [the `Tabs.mdx` example](https://github.com/artsy/palette/blob/master/docs/Tabs.mdx) 
11. Stub out the the new `MyComponent.mdx` file like the example format above and hit save and reload the browser. You should now see it in the sidebar to the left. Click it! 
12. Next, back in Reaction navigate to the old `MyComponent.story.tsx` file and start copying stuff over into the new format in Palette. The example from storybooks should be copy-pasteable, with minor adjustments -- just make sure to import your component [like so](https://github.com/artsy/palette/blob/master/docs/Tabs.mdx#L6). (Note that you might need to add additional imports if the storybooks file uses things like `<Box>` or `<Flex>` or whatever.) Hit save along the way just to make sure everything is working ok. MDX doesn't go through TypeScript, so if you have errors they'll have to be caught in the browser
13. Once the component is imported and the docs are done, check to see if there's a corresponding test on the reaction side and copy that over into a `/elements/MyComponent/__tests__/MyComponent.test.tsx` file. 
14. Save, and then test it via `yarn test`
15. Open a PR, label it as a `Minor` version (since we're adding a new feature), and add me as a reviewer. 
16. Done 🎉 

Once all of the components above have been migrated I'll handle removing them from Reaction (or we can pair on it) since that might be a bit sensitive / cross-dependence-y.

**Comment by dblandin** [comment]
@damassi Looks like all the components we intend to migrate have been migrated. Should we close this issue?

**Comment by damassi** [comment]
@dblandin - I'm going to close once each component has been removed from reaction (I'm going to do that today).
