### ISSUE TITLE
[RFC] New Dependency: Use Flickity instead of Slick

### ISSUE THREAD

**Issue by kierangillen** [artsy/reaction#2343]
https://github.com/artsy/reaction/pull/2329 introduces [Flickity](https://flickity.metafizzy.co/) to Reaction and removes [Slick](https://github.com/akiran/react-slick) from our Carousel component. We are using a React wrapper for this dependency, [React Flickity Component](https://www.npmjs.com/package/react-flickity-component)

We are already using Flickity as a dependency in Force so removing Slick should reduce our bundle. We are replacing Slick with Flickity because Flickity supports more custom options necessary for us to achieve our carousel styling needs. Flickity is also more performant. These out of the box options include:

- `groupCells`, groups carousel slides based on viewport width. This allows for all visible slides to move together to reveal only slides that had not been previously visible.
- `contain`, if enabled the carousel will end with the last slide fully aligned with the right edge of the carousel to remove any remaining whitespace.

With the [options](https://flickity.metafizzy.co/options.html), [methods](https://flickity.metafizzy.co/api.html) and [events](https://flickity.metafizzy.co/events.html) APIs Flickity gives more leverage for custom styling and behavior over Slick. 

Flickity also is more performant while scrolling and allows for rapid carousel advancement. Slick does not support this behavior (each time you click an arrow the carousel must wait to fully settle before advancing). 

Flickity's [bundle](https://bundlephobia.com/result?p=flickity@2.2.0) should also be smaller than [Slicks](https://bundlephobia.com/result?p=react-slick@0.24.0).

**Comment by damassi** [comment]
Since we're already using Flickity in Force, I don't think this RFC is necessary. The API in `Carousel` has remained the same, with some nice additions that we lost when starting to use slick (unaware of Flickity). 

Unless anyone has any objections I think this can be closed?

**Comment by kierangillen** [comment]
Yes I think we wanted to have it more as a record than an official RFC.
