### ISSUE TITLE
Swap artsy-icons font in favor of rendering SVGs directly

### ISSUE THREAD

**Issue by l2succes** [artsy/reaction#24]
Quoting @craigspaeth 

> Since we're paving the future here, I'll throw my 👎 to icon fonts and 👍 to rendering SVGs directly for a couple reasons:
> Icon fonts are a PITA to update b/c you often have to go through some complicated build process to turn the source files into fonts
> They add overhead of mapping font characters to css class name vs. just, essentially, importing the SVG file
> They involve un-intuitive properties, like using font-size to change the size of them
> They're not a cross-platform friendly solution (in case we want to share components with React Native for instance)
> Although a more rare use case, you don't have fine-grain control of the SVG like being able to change things like stroke or animate color fill
> The nicest way I've found to using SVGs directly with React is to use fs.readFileSync and shim fs in the browser or otherwise, but there's other tools that do similar things—the important part is that something takes SVG file in and puts JS out. You can even do this manually to avoid build/tools plugins.
> 
> That said, I like how you've wrapped this in an <Icon> component b/c that could let us decide to swap the implementation underneath pretty easily—so by no means a blocker if we didn't want to go the icon font route.

One of the formats for the icon font is a .svg file so we could just use that file directly and render the icons.

**Comment by alloy** [comment]
> @craigspaeth has good arguments against an icon font, the only thing I have to add is that iOS does not natively support SVG, but I’m sure there’s a way we can make that work.
