### ISSUE TITLE
[fillwidth] Optimise calculations such that it doesn’t freeze the browser.

### ISSUE THREAD

**Issue by alloy** [artsy/reaction#240]
Currently, loading a page like https://www.artsy.net/gene/russia and resizing it a couple of times will freeze the browser, because [the fillwidth component](https://github.com/artsy/reaction/blob/master/src/utils/fillwidth.ts) is trying to recalculate the layout too often.

It would be ideal if we can leverage the browser’s layout engine, by for instance calculating the layout once and then translating the results into relative styling that leave further calculations up to the browser.

Alternatively, a first possible stopgap solution could be to have a single `sizeme` instance that measures the width of the window and passes that down to all the `fullwidth` components.

**Comment by joeyAghion** [comment]
FWIW I encounter this on every page load (at least, of that example page) without any resizes. Let me know if I can help debug!

**Comment by alloy** [comment]
Well this is frustrating. The issue is that [this loop](https://github.com/artsy/reaction/blob/fbd5194a892ee7a263d71e207a717c5ff2db131d/src/utils/fillwidth.ts#L55-L65) never ends and I know how to reproduce it in the browser _on_ the gene page. However, with the exact same inputs I’m not able to reproduce it in a test (both node and browser).

**Comment by alloy** [comment]
Oh, no, I must have recorded some incorrect input, I can reproduce it in a test now.
