### ISSUE TITLE
[RFC] Replace Moment and Moment-Timezone in Reaction and Palette

### ISSUE THREAD

**Issue by kierangillen** [artsy/reaction#2474]
Discover has an [open ticket](https://artsyproduct.atlassian.net/browse/DISCO-1002) to replace Moment and Moment-Timezone with another API and we've talked about switching to [Luxon](https://moment.github.io/luxon).

Currently 47.6% of Reaction's bundle size is attributed to Moment-Timezone.

The bundle size for [Luxon](https://bundlephobia.com/result?p=luxon@1.15.0) is significantly smaller than for [Moment](https://bundlephobia.com/result?p=moment@2.24.0) and [Moment-Timezone](https://bundlephobia.com/result?p=moment-timezone@0.5.25). 

So far, with some experimenting, there seems to be no reason Luxon should not work for our purposes in Reaction and Palette.

**Comment by pepopowitz** [comment]
I'd be curious about edge cases. Have you found any unique/complex uses of timezones with moment-timezone in the existing codebase, or are they all pretty simple?

**Comment by alloy** [comment]
Are there any other alternatives? And, if so, what are the pros/cons and are we perhaps already including one of the alternatives (or luxon) as a transitive dependency?

**Comment by kierangillen** [comment]
@pepopowitz so far I haven't found any situation that can't be handled with Luxon, you can see my tests/work here https://github.com/artsy/reaction/pull/2476

@alloy I'm not an expert on these libraries and would be interested if others have thoughts, but from what I can tell it may come to personal preference as I can't find radical differences between alternative libraries. [Date-FNS](https://date-fns.org/) has a marginally smaller [bundle size](https://date-fns.org/) to Luxon's. I know @ds300 has used Luxon before, curious whether others have opinion or experiences.

**Comment by kierangillen** [comment]
It should be noted that Luxon is maintained by the Moment team, so there may be slightly more support but this is conjecture.

**Comment by anandaroop** [comment]
This caught my eye, from the author's own summary:

> 5. Abuse the Intl API horribly to provide time zone support. Only possible for modern browsers.

I wanted to see what the browser compatibility looked like, and I believe it's summarized in https://github.com/moment/luxon/blob/master/docs/matrix.md — so as an FYI this means we would either not support IE 11 and iOS Safari 9 — or polyfill for them.

**Comment by damassi** [comment]
We currently don't support either of those browsers.

**Comment by anandaroop** [comment]
Thanks @damassi I figured as much 👍 , but struggled to find an authoritative list.

**Comment by damassi** [comment]
https://github.com/damassi/force/blob/1ea02e28d16cb6c743fa24579cdf46f06caf7a83/src/lib/middleware/unsupported_browser.coffee#L8

**Comment by alloy** [comment]
> from what I can tell it may come to personal preference as I can't find radical differences between alternative libraries

While it appears to only be because of dev tooling, we currently already have [date-fns in our bundle](https://github.com/artsy/reaction/blob/7994f52cadd7548dbbdfa0603b17c838370d62b9/yarn.lock#L5265-L5268) and so us using it in our own codebase wouldn’t actually add anything to our bundle.

```
~/C/A/reaction [master] » yarn why date-fns
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "date-fns"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "date-fns@1.29.0"
info Reasons this module exists
   - "concurrently" depends on it
   - Hoisted from "concurrently#date-fns"
   - Hoisted from "lint-staged#listr#listr-verbose-renderer#date-fns"
info Disk size without dependencies: "3.8MB"
info Disk size with unique dependencies: "3.8MB"
info Disk size with transitive dependencies: "3.8MB"
info Number of shared dependencies: 0
✨  Done in 0.94s.
```

Unlike runtime dependencies, these dev dependencies aren’t reason enough imo to choose date-fns, as it won’t ever be pulled into browsers. However, the fact that there’s no Luxon in our bundle but there is 2 dependencies on date-fns, _might_ be in indication that date-fns is the more ubiquitous package. What I’m trying to say is that perhaps using Luxon now means that in the future we end up having both because another of our runtime dependencies may decide to depend on date-fns instead.

Overall, having less dependencies is generally a maintenance win.

**Comment by kierangillen** [comment]
@alloy Just to be clear are you suggesting you'd prefer if we use the date-fns library?

**Comment by damassi** [comment]
@erikdstock - I recall you mentioning a while back that you've used date-fns before and had to replace it with luxon because something was funny with TZ support? (I could be misremembering.)

**Comment by alloy** [comment]
@kierangillen If all else is equal [enough], yeah

**Comment by erikdstock** [comment]
@damassi If I recall I tried date-fns but then moved back to moment for the TZ support. I don't think I'd heard of luxon.

**Comment by zephraph** [comment]
Date-fns doesn’t currently have timezone support. It’s suppose to get it in v2 which is WIP, but that’s been in the works for a while. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kierangillen** [comment]
Given date-fns lack of timezone support, I'm opting to use Luxon and closing this issue.

**Comment by alloy** [comment]
There appears to be a complimentary lib available https://github.com/marnusw/date-fns-tz, which notes:

> Dependency free IANA time zone support is implemented via the Intl API to keep actual time zone data out of code bundles. Modern browsers all support the necessary features, and for those that don't a polyfill can be used.

**Comment by alloy** [comment]
There’s also another that does bundle the database https://www.npmjs.com/package/date-fns-timezone

**Comment by kierangillen** [comment]
@alloy @zephraph Given all of the above, does one of you want to make the call on which we should use?

**Comment by damassi** [comment]
Note that `luxon` is Moment's explicit spiritual successor. We might be setting ourselves up for future success by staying in the family.

**Comment by damassi** [comment]
Also, [Luxon has 23 issues](https://github.com/moment/luxon/issues) and [date-fns has 127](https://github.com/date-fns/date-fns/issues). The moment ecosystem is better supported.

**Comment by kierangillen** [comment]
Moving forward with Luxon based on above comments referencing timezone support and a better supported ecosystem.

**Comment by zephraph** [comment]
Sorry I was late on this, but I'm 👍. I've used date-fns in the past and while I prefer its API in many cases it doesn't have tz support and won't until the 2.0 release (which has been pending for a while now).
