### ISSUE TITLE
Pretty text at the top got broke

### ISSUE THREAD

**Issue by orta** [artsy/reaction#2675]
Maybe prettier somehow?

![Screen Shot 2019-08-08 at 4 50 58 PM](https://user-images.githubusercontent.com/49038/62736984-c173ce00-b9fc-11e9-8fba-591eb38adea1.png)

**Comment by dblandin** [comment]
@orta Thanks for the nudge on this!

Looks like a @fossabot script must have removed the leading indentation at the top of the file, causing the code block to break: https://github.com/artsy/reaction/pull/2449

All fixed now!
