### ISSUE TITLE
Update TypeScript/prettier/tslint/storybooks etc

### ISSUE THREAD

**Issue by orta** [artsy/reaction#437]
Now that the mega PR is wrapped, and VS Code's runtime error check is update to TS 2.6 - reaction devs will be seeing new React errors that won't show up in `yarn type-check`

**Comment by alloy** [comment]
Why do they not show in `yarn type-check` and can we make it do that after all?

**Comment by orta** [comment]
`yarn type-check` uses our locked to 2.3 version
the inline errors in vscode us the same version as vscode's TS, which is 2.6

We can make them match by updating TypeScript 👍

**Comment by alloy** [comment]
Ahh, I see 👍
