### ISSUE TITLE
Get rid of dot-dot relative paths

### ISSUE THREAD

**Issue by alloy** [artsy/reaction#55]
https://github.com/artsy/force/issues/942

This is a task for after launching the loyalty registration program.

**Comment by orta** [comment]
@damassi feel up for trying this?

**Comment by damassi** [comment]
Once I'm a bit further along on [this journey](https://github.com/artsy/force/pull/1571) I can definitely take a look but its going to be a little bit. 

(Also, as a technical issue, I've run into problems aligning client / server babel / ts path resolution over in Prediction, so some additional experimentation is needed; I don't think it will be as simple as dropping the babel plugin in `.babelrc` but I could be wrong.)

**Comment by orta** [comment]
👍
