### ISSUE TITLE
Peril rule to remind devs to upgrade version via commit message

### ISSUE THREAD

**Issue by kanaabe** [artsy/reaction#585]
Sometimes we forget to include a release message such as `[FEATURE news] Some news thing` in a commit to publish a new version of Reaction to npm. Would be nice if we could be reminded if that doesn't exist as a warning. cc @orta

**Comment by orta** [comment]
This is tricky, what metrics would you use to denote that it might be shippable? You probably don’t want every PR having this

**Comment by kanaabe** [comment]
Yeah good point, I guess I've noticed that all my recent PRs fall into one of these categories:
> PATCH, DOC, FIX, FEATURE, and BREAKING

So I probably _would_ prefer it on every PR. Not as an error but a warning.

**Comment by orta** [comment]
I think the least noisy way to attack this is to set up [Danger as a pre-push linter](https://github.com/danger/danger-js/blob/master/CHANGELOG.md#310) and highlight if there's not one of those e.g. in package.json

```json
{
  "scripts": {
    "prepush": "yarn build; yarn danger:prepush"
  }
}
```

and make a separate dangerfile for this checks ( I do this in [danger-js for CHANGELOGs](https://github.com/danger/danger-js/blob/master/dangerfile.lite.ts))

**Comment by eessex** [comment]
Agreed that a warning/reminder would be helpful -- I often forget to include these!  Also have not had a change since semantic-release was added that did not make sense for a version bump of some kind.
