### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by eessex** [artsy/reaction#587]
I believe semantic release has the ability to auto-generate a changelog based on commit messages -- I think this could be a helpful addition to keep track of what is included in each version.

**Comment by dblandin** [comment]
Looks like this was addressed with https://github.com/artsy/reaction/pull/1779!

We decided to add changelog entries automatically based on the pull requests included in each release.

@eessex Ready to close?

**Comment by zephraph** [comment]
We've got changelogs now, I'm gonna close. 👍
