### ISSUE TITLE
Get rid of coffee-script/register in dependencies

### ISSUE THREAD

**Issue by alloy** [artsy/reaction#65]
- [ ] artsy-passport

**Comment by orta** [comment]
https://github.com/artsy/artsy-passport/pull/112

**Comment by alloy** [comment]
👏 

Was that the only one (and can this be closed) or do we still have other CS deps?

**Comment by orta** [comment]
Just this

![screen shot 2017-06-28 at 10 10 42](https://user-images.githubusercontent.com/49038/27641514-10ffcb2c-5bea-11e7-91bf-6ca83de734f6.png)

**Comment by orta** [comment]
Fixed with https://github.com/artsy/reaction/pull/185
