### ISSUE TITLE
Wizard - You should not use <Route> or withRouter() outside a <Router>

### ISSUE THREAD

**Issue by alejandronanez** [artsy/reaction#834]
Storybook issue.

<img width="1011" alt="screen shot 2018-06-20 at 12 06 06 pm" src="https://user-images.githubusercontent.com/464978/41673382-65abbb20-7482-11e8-9cc0-8699072f6b65.png">

**Comment by hafbau** [comment]
For future visitors, see this issue: https://github.com/storybookjs/storybook/issues/769
